updated to all luarocks

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,8 +2,17 @@
 
 install_luaJIT() {
   local install_type=$1
-  local version=$2
+  local raw_version=$2
   local install_path=$3
+  local luaJIT_version=$(echo $raw_version | sed -e 's/--.*$//g')
+  local lua_rocks_version=$(echo $raw_version | sed -e "s/^.*--//g")
+
+  echo $raw_version
+  echo "==============="
+  echo $luaJIT_version
+  echo "---------------"
+  echo $lua_rocks_version
+  echo "==============="
 
   if [ "$TMPDIR" = "" ]; then
     local tmp_download_dir=$(mktemp -d)
@@ -11,31 +20,49 @@ install_luaJIT() {
     local tmp_download_dir=$TMPDIR
   fi
 
-  local source_path=$(get_download_file_path $install_type $version $tmp_download_dir)
-  download_source $install_type $version $source_path
+  local luaJIT_source_path=$(get_luaJIT_download_file_path $install_type $luaJIT_version $tmp_download_dir)
+  local lua_rocks_source_path=$(get_lua_rocks_download_file_path $install_type $lua_rocks_version $tmp_download_dir)
+  download_luaJIT_source $install_type $luaJIT_version $luaJIT_source_path
+  download_lua_rocks_source $install_type $lua_rocks_version $lua_rocks_source_path
 
   # running this in a subshell
   # because we don't want to disturb current working dir
   (
-    cd $(dirname $source_path)
-    tar zxf $source_path || exit 1
-    cd $(untar_path $install_type $version $tmp_download_dir)
+    cd $(dirname $luaJIT_source_path)
+    tar zxf $luaJIT_source_path || exit 1
+    cd $(untar_luaJIT_path $install_type $luaJIT_version $tmp_download_dir)
 
-    local configure_options="$(construct_configure_options)"
+    local luaJIT_configure_options="$(construct_luaJIT_configure_options)"
     # set in os_based_configure_options
     # we unset it here because echo-ing changes the return value of the function
     unset ASDF_PKG_MISSING
 
-    echo "Building with options: $configure_options"
-    make $configure_options || exit 1
-    make install $configure_options || exit 1
+    echo "Building luaJIT with options: $luaJIT_configure_options"
+    make $luaJIT_configure_options || exit 1
+    make install $luaJIT_configure_options || exit 1
+
+    ##########################################################################
+
+    cd $(dirname $lua_rocks_source_path)
+    tar zxf $lua_rocks_source_path || exit 1
+    cd $(untar_lua_rocks_path $install_type $lua_rocks_version $tmp_download_dir)
+
+    local lua_rocks_configure_options="$(construct_lua_rocks_configure_options)"
+    # set in os_based_configure_options
+    # we unset it here because echo-ing changes the return value of the function
+    unset ASDF_PKG_MISSING
+
+    echo "Building luarocks with options: $lua_rocks_configure_options"
+    ./configure $lua_rocks_configure_options || exit 1
+    make build || exit 1
+    make install || exit 1
   )
 }
 
 
-construct_configure_options() {
+construct_luaJIT_configure_options() {
   if [ "$LUAJIT_CONFIGURE_OPTIONS" = "" ]; then
-    local configure_options="$(os_based_configure_options) PREFIX=$install_path"
+    local configure_options="$(os_based_luaJIT_configure_options) PREFIX=$install_path"
 
     if [ "$LUAJIT_EXTRA_CONFIGURE_OPTIONS" != "" ]; then
       configure_options="$configure_options $LUAJIT_EXTRA_CONFIGURE_OPTIONS"
@@ -48,13 +75,37 @@ construct_configure_options() {
 }
 
 
-os_based_configure_options() {
+construct_lua_rocks_configure_options() {
+  luaJIT_version=$1
+  if [ "$LUAROCKS_CONFIGURE_OPTIONS" = "" ]; then
+    local luaJIT_include_version="$(ls $install_path/include | head -1)"
+    local luaJIT_include_path="$install_path/include/$luaJIT_include_version"
+    local configure_options="$(os_based_lua_rocks_configure_options) --prefix=$install_path --lua-suffix=jit --with-lua=$install_path --with-lua-include=$luaJIT_include_path"
+
+    if [ "$LUAROCKS_EXTRA_CONFIGURE_OPTIONS" != "" ]; then
+      configure_options="$configure_options $LUAROCKS_EXTRA_CONFIGURE_OPTIONS"
+    fi
+  else
+    local configure_options="$LUAROCKS_CONFIGURE_OPTIONS PREFIX=$install_path"
+  fi
+
+  echo "$configure_options"
+}
+
+
+os_based_luaJIT_configure_options() {
   local configure_options=""
   echo $configure_options
 }
 
 
-untar_path() {
+os_based_lua_rocks_configure_options() {
+  local configure_options=""
+  echo $configure_options
+}
+
+
+untar_luaJIT_path() {
   local install_type=$1
   local version=$2
   local tmp_download_dir=$3
@@ -68,17 +119,40 @@ untar_path() {
 }
 
 
-download_source() {
+untar_lua_rocks_path() {
+  local install_type=$1
+  local version=$2
+  local tmp_download_dir=$3
+
+  if [ "$install_type" = "version" ]
+  then
+    echo "$tmp_download_dir/luarocks-${version}"
+  else
+    echo "$tmp_download_dir/luarocks-${version}"
+  fi
+}
+
+
+download_luaJIT_source() {
   local install_type=$1
   local version=$2
   local download_path=$3
-  local download_url=$(get_download_url $install_type $version)
+  local download_url=$(get_luaJIT_download_url $install_type $version)
+
+  curl -Lo $download_path -C - $download_url
+}
+
+download_lua_rocks_source() {
+  local install_type=$1
+  local version=$2
+  local download_path=$3
+  local download_url=$(get_lua_rocks_download_url $install_type $version)
 
   curl -Lo $download_path -C - $download_url
 }
 
 
-get_download_file_path() {
+get_luaJIT_download_file_path() {
   local install_type=$1
   local version=$2
   local tmp_download_dir=$3
@@ -88,10 +162,27 @@ get_download_file_path() {
 }
 
 
-get_download_url() {
+get_lua_rocks_download_file_path() {
+  local install_type=$1
+  local version=$2
+  local tmp_download_dir=$3
+  local pkg_name="luarocks-${version}.tar.gz"
+
+  echo "$tmp_download_dir/$pkg_name"
+}
+
+
+get_luaJIT_download_url() {
   local install_type=$1
   local version=$2
   echo "http://luajit.org/download/LuaJIT-${version}.tar.gz"
+}
+
+
+get_lua_rocks_download_url() {
+  local install_type=$1
+  local version=$2
+  echo "http://luarocks.github.io/luarocks/releases/luarocks-${version}.tar.gz"
 }
 
 
